// examples/electron-apps/electron-react-app/src/App.tsx
import { useEffect, useRef } from "react";
import { createJsonScene } from "threejson";
import "./App.css";

const SCENE_JSON_URL = "./demo-assets/scene/sceneRuntimeBasic.json";

export default function App() {
  const wrapRef = useRef<HTMLDivElement | null>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const rtRef = useRef<Awaited<ReturnType<typeof createJsonScene>> | null>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    const wrap = wrapRef.current;
    if (!canvas || !wrap) return;

    let alive = true;
    let resizeObserver: ResizeObserver | null = null;

    void (async () => {
      const res = await fetch(SCENE_JSON_URL);
      if (!res.ok) {
        throw new Error(`Failed to load scene JSON: ${res.status} ${SCENE_JSON_URL}`);
      }
      const sceneRuntimeBasic = (await res.json()) as Record<string, unknown>;
      const data = JSON.parse(JSON.stringify(sceneRuntimeBasic)) as Record<string, unknown>;

      data.canvasWidth = wrap.clientWidth;
      data.canvasHeight = wrap.clientHeight;
      const created = await createJsonScene(data, { canvas, resetScene: true });
      if (!alive) {
        created.stop();
        created.dispose();
        return;
      }
      rtRef.current = created;
      created.start();

      resizeObserver = new ResizeObserver(() => {
        rtRef.current?.resize?.({
          width: wrap.clientWidth,
          height: wrap.clientHeight
        });
      });
      resizeObserver.observe(wrap);
    })();

    return () => {
      alive = false;
      resizeObserver?.disconnect();
      const r = rtRef.current;
      rtRef.current = null;
      r?.stop();
      r?.dispose();
    };
  }, []);

  return (
    <div ref={wrapRef} className="stage">
      <canvas ref={canvasRef} />
    </div>
  );
}

// examples/electron-apps/electron-vue/src/App.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, shallowRef } from "vue";
import { createJsonScene } from "threejson";

const SCENE_JSON_URL = "./demo-assets/scene/sceneRuntimeBasic.json";

const canvasEl = ref<HTMLCanvasElement | null>(null);
const wrapEl = ref<HTMLDivElement | null>(null);
const runtime = shallowRef<Awaited<ReturnType<typeof createJsonScene>> | null>(null);
let resizeObserver: ResizeObserver | null = null;

onMounted(async () => {
  const canvas = canvasEl.value;
  const wrap = wrapEl.value;
  if (!canvas || !wrap) return;

  const res = await fetch(SCENE_JSON_URL);
  if (!res.ok) {
    throw new Error(`Failed to load scene JSON: ${res.status} ${SCENE_JSON_URL}`);
  }
  const sceneRuntimeBasic = (await res.json()) as Record<string, unknown>;
  const data = JSON.parse(JSON.stringify(sceneRuntimeBasic)) as Record<string, unknown>;
  data.canvasWidth = wrap.clientWidth;
  data.canvasHeight = wrap.clientHeight;

  const rt = await createJsonScene(data, { canvas, resetScene: true });
  rt.start();
  runtime.value = rt;

  resizeObserver = new ResizeObserver(() => {
    rt.resize?.({ width: wrap.clientWidth, height: wrap.clientHeight });
  });
  resizeObserver.observe(wrap);
});

onBeforeUnmount(() => {
  resizeObserver?.disconnect();
  resizeObserver = null;
  const rt = runtime.value;
  rt?.stop?.();
  rt?.dispose?.();
  runtime.value = null;
});
</script>

<template>
  <div ref="wrapEl" class="stage">
    <canvas ref="canvasEl" />
  </div>
</template>

<style scoped>
.stage {
  width: 100vw;
  height: 100vh;
  margin: 0;
  overflow: hidden;
  background: #222;
}
canvas {
  display: block;
  width: 100%;
  height: 100%;
}
</style>
